In [2]:
import pandas as pd
import numpy as np

clients = pd.read_csv("data/raw/clients.csv", parse_dates=["join_date"])
trades = pd.read_csv("data/raw/trades.csv", parse_dates=["date"])
fx_daily = pd.read_csv("data/raw/fx_daily.csv", parse_dates=["date"])

print(f"\nclients df = {clients.shape}")
clients.info()
print(f"\ntrades df = {trades.shape}")
trades.info()
print(f"\nfx_daily df = {fx_daily.shape}")
fx_daily.info()

print(f"\ntrades df\n{trades['profit_usd'].describe()}")
print(f"\nclient df by country\n{clients['country'].value_counts()}")
print(f"\ntrade df by pair\n{trades['pair'].value_counts()}")

clients df = (200, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   client_id     200 non-null    int64
 1   country       200 non-null    object
 2   account_type  200 non-null    object
 3   join_date     200 non-null    datetime64[ns]
 4   deposit_usd   200 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 7.9+ KB

trades df = (3000, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   trade_id    3000 non-null   int64
 1   date        3000 non-null   datetime64[ns]
 2   client_id   3000 non-null   int64
 3   pair        3000 non-null   object
 4   side        3000 non-null   object
 5   lots        3000 non-null   float64
 6   profit_usd  3000 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 164.2+ KB

fx_daily df = (1044, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1044 non-null   datetime64[ns]
 1   pair    1044 non-null   object
 2   open    1044 non-null   float64
 3   high    1044 non-null   float64
 4   low     1044 non-null   float64
 5   close   1044 non-null   float64
 6   volume  1044 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 57.2+ KB

trades df
count    3000.000000
mean        5.753733
std        57.524627
min      -410.870000
25%        -2.092500
50%         0.530000
75%         6.462500
max       611.450000
Name: profit_usd, dtype: float64

client df by country
country
Malaysia       50
Thailand       49
Indonesia      34
Vietnam        29
Singapore      21
Philippines    17
Name: count, dtype: int64

trade df by pair
pair
XAUUSD    771
EURUSD    757
GBPUSD    752
USDJPY    720
Name: count, dtype: int64

In [3]:
print(f"\n{trades[trades['profit_usd'] > 0]}")
print(f"\n{trades[(trades['pair'] == 'XAUUSD') & (trades['lots'] >= 1.0)]}")
print(f"\n{clients[clients['country'].isin(['Thailand', 'Malaysia'])]}")
print(f"\n{trades.nlargest(10, 'profit_usd')}")
print(f"\n{fx_daily[(fx_daily['pair'] == 'EURUSD') & (fx_daily['date'].dt.year == 2026) & (fx_daily['date'].dt.month == 1)]}")

      trade_id       date  client_id    pair  side  lots  profit_usd
0         2905 2025-07-01         89  XAUUSD   buy  1.00       74.97
1         1713 2025-07-01         27  EURUSD   buy  2.00       69.01
2          730 2025-07-01         58  GBPUSD  sell  0.05        0.17
3         2438 2025-07-01        197  EURUSD  sell  1.00      241.01
4         2623 2025-07-01          9  EURUSD   buy  0.10        1.18
...        ...        ...        ...     ...   ...   ...         ...
2992      2467 2026-06-30        120  XAUUSD   buy  0.50       97.86
2993       739 2026-06-30         40  XAUUSD   buy  0.10       24.30
2995      1903 2026-06-30        102  EURUSD   buy  0.01        1.05
2996      1784 2026-06-30        100  USDJPY  sell  0.05        0.78
2997        31 2026-06-30        144  GBPUSD   buy  0.01        0.95

[1734 rows x 7 columns]

      trade_id       date  client_id    pair  side  lots  profit_usd
0         2905 2025-07-01         89  XAUUSD   buy   1.0       74.97
14         178 2025-07-02          6  XAUUSD  sell   2.0     -249.89
119        239 2025-07-15        114  XAUUSD   buy   1.0      183.05
121       2209 2025-07-15          5  XAUUSD  sell   1.0      271.45
235       1394 2025-07-29         72  XAUUSD  sell   1.0       83.38
...        ...        ...        ...     ...   ...   ...         ...
2903      2534 2026-06-18        188  XAUUSD   buy   2.0     -140.34
2925      1331 2026-06-22        196  XAUUSD  sell   1.0      -32.04
2972        11 2026-06-29        128  XAUUSD   buy   1.0       43.12
2974      2382 2026-06-29         19  XAUUSD  sell   1.0       92.84
2999       881 2026-06-30        120  XAUUSD  sell   1.0     -130.19

[124 rows x 7 columns]

     client_id   country account_type  join_date  deposit_usd
0            1  Malaysia      cTrader 2026-04-12          500
1            2  Thailand      cTrader 2025-10-17         1000
2            3  Thailand   Raw Spread 2026-03-23         2500
3            4  Thailand     Standard 2026-04-05          500
4            5  Thailand      cTrader 2025-12-05          500
..         ...       ...          ...        ...          ...
189        190  Malaysia   Raw Spread 2025-11-16         1000
190        191  Thailand     Standard 2025-12-11         5000
191        192  Thailand   Raw Spread 2025-08-24         1000
194        195  Malaysia     Standard 2025-08-09         5000
195        196  Thailand     Standard 2026-03-03         1000

[99 rows x 5 columns]

      trade_id       date  client_id    pair  side  lots  profit_usd
766        713 2025-10-02         69  XAUUSD   buy   2.0      611.45
583       2306 2025-09-05         93  XAUUSD  sell   2.0      528.63
1028      1276 2025-11-07        190  XAUUSD   buy   2.0      445.00
2643      1651 2026-05-21        190  XAUUSD   buy   2.0      436.27
2404      1444 2026-04-22         54  XAUUSD  sell   2.0      361.97
1311      1204 2025-12-16        148  USDJPY  sell   2.0      357.46
839       2104 2025-10-15        177  GBPUSD  sell   2.0      356.58
2117      2130 2026-03-23        103  GBPUSD   buy   2.0      356.14
1264      2462 2025-12-10         51  XAUUSD   buy   1.0      347.23
2638      1140 2026-05-21        176  EURUSD   buy   2.0      342.19

          date    pair     open     high      low    close  volume
132 2026-01-01  EURUSD  1.01405  1.01918  1.01039  1.01478   37944
133 2026-01-02  EURUSD  1.01478  1.01115  1.00634  1.00875   28157
134 2026-01-05  EURUSD  1.00875  1.01457  1.01341  1.01399   44905
135 2026-01-06  EURUSD  1.01399  1.02070  1.01938  1.02004   51831
136 2026-01-07  EURUSD  1.02004  1.02304  1.01691  1.01998   57337
137 2026-01-08  EURUSD  1.01998  1.02436  1.01376  1.01906   46553
138 2026-01-09  EURUSD  1.01906  1.02101  1.01622  1.01861   10030
139 2026-01-12  EURUSD  1.01861  1.01538  1.01431  1.01484   23517
140 2026-01-13  EURUSD  1.01484  1.02071  1.01831  1.01951   34048
141 2026-01-14  EURUSD  1.01951  1.01865  1.01635  1.01750    9262
142 2026-01-15  EURUSD  1.01750  1.02063  1.01435  1.01749   28002
143 2026-01-16  EURUSD  1.01749  1.01511  1.01383  1.01447   12272
144 2026-01-19  EURUSD  1.01447  1.01581  1.00844  1.01213   35470
145 2026-01-20  EURUSD  1.01213  1.00997  1.00435  1.00716   15134
146 2026-01-21  EURUSD  1.00716  1.01487  1.00998  1.01242   19908
147 2026-01-22  EURUSD  1.01242  1.01341  1.01059  1.01200   21715
148 2026-01-23  EURUSD  1.01200  1.02190  1.01033  1.01612   58527
149 2026-01-26  EURUSD  1.01612  1.02048  1.01226  1.01637   29613
150 2026-01-27  EURUSD  1.01637  1.01557  1.01193  1.01375   35570
151 2026-01-28  EURUSD  1.01375  1.01671  1.00855  1.01263   56039
152 2026-01-29  EURUSD  1.01263  1.01173  1.00940  1.01056    5762
153 2026-01-30  EURUSD  1.01056  1.01170  1.00990  1.01080   20312

In [4]:
trades.groupby("pair")["profit_usd"].sum()

pair
EURUSD    5148.46
GBPUSD    4741.21
USDJPY    3867.33
XAUUSD    3504.20
Name: profit_usd, dtype: float64

In [5]:
trades.groupby("pair").agg(
    total_profit = ("profit_usd", "sum"),
    avg_profit = ("profit_usd", "mean"),
    total_trades = ("profit_usd", "count"),
    total_lots = ("lots", "sum")
).sort_values(["total_lots", "total_trades"], ascending=[False, True])

        total_profit  avg_profit  total_trades  total_lots
pair
XAUUSD       3504.20    4.545006           771      252.96
USDJPY       3867.33    5.371292           720      237.32
EURUSD       5148.46    6.801136           757      232.64
GBPUSD       4741.21    6.304801           752      226.86

In [6]:
trades.groupby(["pair", "side"])["profit_usd"].mean()

pair    side
EURUSD  buy     7.121931
        sell    6.481187
GBPUSD  buy     4.700273
        sell    7.826192
USDJPY  buy     1.394448
        sell    8.831662
XAUUSD  buy     3.477220
        sell    5.757729
Name: profit_usd, dtype: float64

In [7]:
trades.pivot_table(index="pair", columns="side", values="profit_usd", aggfunc="mean")

side         buy      sell
pair
EURUSD  7.121931  6.481187
GBPUSD  4.700273  7.826192
USDJPY  1.394448  8.831662
XAUUSD  3.477220  5.757729

In [13]:
trades["pair_avg"] = trades.groupby("pair")["profit_usd"].transform("mean")
print(trades)

      trade_id       date  client_id    pair  side  lots  profit_usd  pair_avg
0         2905 2025-07-01         89  XAUUSD   buy  1.00       74.97  4.545006
1         1713 2025-07-01         27  EURUSD   buy  2.00       69.01  6.801136
2          730 2025-07-01         58  GBPUSD  sell  0.05        0.17  6.304801
3         2438 2025-07-01        197  EURUSD  sell  1.00      241.01  6.801136
4         2623 2025-07-01          9  EURUSD   buy  0.10        1.18  6.801136
...        ...        ...        ...     ...   ...   ...         ...       ...
2995      1903 2026-06-30        102  EURUSD   buy  0.01        1.05  6.801136
2996      1784 2026-06-30        100  USDJPY  sell  0.05        0.78  5.371292
2997        31 2026-06-30        144  GBPUSD   buy  0.01        0.95  6.304801
2998      1282 2026-06-30         56  USDJPY  sell  0.10       -0.62  5.371292
2999       881 2026-06-30        120  XAUUSD  sell  1.00     -130.19  4.545006

[3000 rows x 8 columns]

In [17]:
trades["vs_avg"] = trades["profit_usd"] - trades["pair_avg"]
print(trades)

      trade_id       date  client_id    pair  side  lots  profit_usd  \
0         2905 2025-07-01         89  XAUUSD   buy  1.00       74.97
1         1713 2025-07-01         27  EURUSD   buy  2.00       69.01
2          730 2025-07-01         58  GBPUSD  sell  0.05        0.17
3         2438 2025-07-01        197  EURUSD  sell  1.00      241.01
4         2623 2025-07-01          9  EURUSD   buy  0.10        1.18
...        ...        ...        ...     ...   ...   ...         ...
2995      1903 2026-06-30        102  EURUSD   buy  0.01        1.05
2996      1784 2026-06-30        100  USDJPY  sell  0.05        0.78
2997        31 2026-06-30        144  GBPUSD   buy  0.01        0.95
2998      1282 2026-06-30         56  USDJPY  sell  0.10       -0.62
2999       881 2026-06-30        120  XAUUSD  sell  1.00     -130.19

      pair_avg      vs_avg
0     4.545006   70.424994
1     6.801136   62.208864
2     6.304801   -6.134801
3     6.801136  234.208864
4     6.801136   -5.621136
...        ...         ...
2995  6.801136   -5.751136
2996  5.371292   -4.591292
2997  6.304801   -5.354801
2998  5.371292   -5.991292
2999  4.545006 -134.735006

[3000 rows x 9 columns]

In [20]:
for pair, group in trades.groupby("pair"):
    print(pair, len(group))

EURUSD 757
GBPUSD 752
USDJPY 720
XAUUSD 771